/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  11155111: {
    CommunityPortal: {
      address: "0x5BD8669A700565a5237671ee33A5Cc4cDaBF01bF",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "uint256[2]",
                  name: "_pA",
                  type: "uint256[2]",
                },
                {
                  internalType: "uint256[2][2]",
                  name: "_pB",
                  type: "uint256[2][2]",
                },
                {
                  internalType: "uint256[2]",
                  name: "_pC",
                  type: "uint256[2]",
                },
                {
                  internalType: "uint256[38]",
                  name: "_pubSignals",
                  type: "uint256[38]",
                },
              ],
              internalType: "struct CommunityPortal.ProofArgs",
              name: "proof",
              type: "tuple",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "addCommunityCollaborator",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "communityPortal",
          outputs: [
            {
              internalType: "contract FileversePortal",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256[38]",
              name: "_pubSignals",
              type: "uint256[38]",
            },
          ],
          name: "getSignerFromPublicSignals",
          outputs: [
            {
              internalType: "uint256[2]",
              name: "",
              type: "uint256[2]",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256[38]",
              name: "_pubSignals",
              type: "uint256[38]",
            },
          ],
          name: "getValidEventIdFromPublicSignals",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256[38]",
              name: "_pubSignals",
              type: "uint256[38]",
            },
          ],
          name: "getWaterMarkFromPublicSignals",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "isCollaborator",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "trustedForwarder",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256[2]",
              name: "_pA",
              type: "uint256[2]",
            },
            {
              internalType: "uint256[2][2]",
              name: "_pB",
              type: "uint256[2][2]",
            },
            {
              internalType: "uint256[2]",
              name: "_pC",
              type: "uint256[2]",
            },
            {
              internalType: "uint256[38]",
              name: "_pubSignals",
              type: "uint256[38]",
            },
          ],
          name: "verifyProof",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
